site_name: Reino Carpa
theme:
  name: material
  language: es
  palette:
    primary: custom

    
    
nav:
  - Inicio: index.md
  - Reglas: rules.md
  - Roles:
    - Aventurero: roles/adventurer.md
    - Mercenario: roles/mercenary.md
    - Nobleza: roles/nobility.md
    - Guardia Real: roles/royal-guard.md
    
extra_css:
  - css/styles.css
